server:
  port: 4004

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service-route
          uri: http://auth-service:4005
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1


        - id: patient-service-route
          uri: http://patient-service:4000
          predicates:
            - Path=/api/patients, /api/patients/**
          filters:
            - StripPrefix=1
            - JwtValidation

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG